export const items = [
  {
    movieId: 1,
    nameRU: '33 слова о дизайне',
    duration: '1ч 47м',
    image: 'https://i.ibb.co/kH15c8d/1.jpg',
    trailerLink: 'https://youtu.be/3WaA4oH-5R4',
  },
  {
    movieId: 2,
    nameRU: '33 слова о дизайне',
    duration: '1ч 47м',
    image: 'https://i.ibb.co/bX41cYx/2.jpg',
    trailerLink: 'https://youtu.be/3WaA4oH-5R4',
  },
  {
    movieId: 3,
    nameRU: '33 слова о дизайне',
    duration: '1ч 47м',
    image: 'https://i.ibb.co/Bqyy2Mw/3.jpg',
    trailerLink: 'https://youtu.be/3WaA4oH-5R4',
    isActive: true,
  },
  {
    movieId: 4,
    nameRU: '33 слова о дизайне',
    duration: '1ч 47м',
    image: 'https://i.ibb.co/Yp395Vf/4.jpg',
    trailerLink: 'https://youtu.be/3WaA4oH-5R4',
  },
  {
    movieId: 5,
    nameRU: '33 слова о дизайне',
    duration: '1ч 47м',
    image: 'https://i.ibb.co/PQFBX21/5.jpg',
    trailerLink: 'https://youtu.be/3WaA4oH-5R4',
    isActive: true,
  },
  {
    movieId: 6,
    nameRU: '33 слова о дизайне',
    duration: '1ч 47м',
    image: 'https://i.ibb.co/hfwTHQS/6.jpg',
    trailerLink: 'https://youtu.be/3WaA4oH-5R4',
  },
  {
    movieId: 7,
    nameRU: '33 слова о дизайне',
    duration: '1ч 47м',
    image: 'https://i.ibb.co/YbnGNx1/7.jpg',
    trailerLink: 'https://youtu.be/3WaA4oH-5R4',
  },
  {
    movieId: 8,
    nameRU: '33 слова о дизайне',
    duration: '1ч 47м',
    image: 'https://i.ibb.co/HNBHfB9/8.jpg',
    trailerLink: 'https://youtu.be/3WaA4oH-5R4',
  },
  {
    movieId: 9,
    nameRU: '33 слова о дизайне',
    duration: '1ч 47м',
    image: 'https://i.ibb.co/NxR67tx/9.jpg',
    trailerLink: 'https://youtu.be/3WaA4oH-5R4',
  },
  {
    movieId: 10,
    nameRU: '33 слова о дизайне',
    duration: '1ч 47м',
    image: 'https://i.ibb.co/HtfbXj4/10.jpg',
    trailerLink: 'https://youtu.be/3WaA4oH-5R4',
    isActive: true,
  },
  {
    movieId: 11,
    nameRU: '33 слова о дизайне',
    duration: '1ч 47м',
    image: 'https://i.ibb.co/gwqQ3XH/11.jpg',
    trailerLink: 'https://youtu.be/3WaA4oH-5R4',
  },
  {
    movieId: 12,
    nameRU: '33 слова о дизайне',
    duration: '1ч 47м',
    image: 'https://i.ibb.co/KhqgpbS/12.jpg',
    trailerLink: 'https://youtu.be/3WaA4oH-5R4',
  },
];
